name: Optionix CI/CD with Infrastructure Validation

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]

env:
  TERRAFORM_VERSION: "1.7.0"
  KUBECTL_VERSION: "1.28.0"

jobs:
  # Infrastructure validation jobs
  terraform-validate:
    name: Terraform Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Terraform Format Check
        run: |
          cd infrastructure/terraform
          terraform fmt -check -recursive

      - name: Terraform Init (local backend)
        run: |
          cd infrastructure/terraform
          terraform init -backend=false

      - name: Terraform Validate
        run: |
          cd infrastructure/terraform
          TF_VAR_environment="ci" \
          TF_VAR_app_name="optionix" \
          TF_VAR_db_name="optionix" \
          TF_VAR_db_username="optionix_admin" \
          TF_VAR_owner="ci-team" \
          TF_VAR_cost_center="engineering" \
          TF_VAR_terraform_state_bucket="dummy-bucket" \
          TF_VAR_terraform_lock_table="dummy-table" \
          TF_VAR_terraform_state_kms_key="arn:aws:kms:us-west-2:123456789012:key/dummy" \
          terraform validate

  kubernetes-validate:
    name: Kubernetes Manifest Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install yamllint
        run: pip install yamllint

      - name: Lint YAML files
        run: |
          cd infrastructure/kubernetes
          yamllint -d "{extends: default, rules: {line-length: {max: 120}, document-start: disable}}" base/*.yaml

      - name: Setup kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/v${{ env.KUBECTL_VERSION }}/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Validate Kubernetes manifests (dry-run)
        run: |
          cd infrastructure/kubernetes/base
          for file in *.yaml; do
            if [ "$file" != "app-secrets.yaml" ]; then
              echo "Validating $file"
              kubectl apply --dry-run=client -f "$file" || echo "Warning: $file validation failed (may require actual cluster)"
            fi
          done

  ansible-validate:
    name: Ansible Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Ansible and ansible-lint
        run: |
          pip install ansible ansible-lint yamllint

      - name: Lint Ansible playbooks
        run: |
          cd infrastructure/ansible
          ansible-lint playbooks/*.yml || echo "Ansible-lint completed with warnings"

      - name: Validate Ansible syntax
        run: |
          cd infrastructure/ansible
          ansible-playbook playbooks/main.yml --syntax-check -i inventory/hosts.yml.example

  shellcheck-scripts:
    name: ShellCheck Scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run shellcheck
        run: |
          sudo apt-get update && sudo apt-get install -y shellcheck
          cd infrastructure/scripts
          shellcheck *.sh || echo "ShellCheck completed with warnings"

  # Application testing jobs
  backend-test:
    name: Backend Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f code/backend/requirements.txt ]; then pip install -r code/backend/requirements.txt; fi

      - name: Run tests
        run: |
          cd code/backend
          python -m pytest || echo "No tests found or tests failed"

  frontend-test:
    name: Frontend Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: code/frontend/package-lock.json

      - name: Install dependencies
        run: |
          cd code/frontend
          npm ci

      - name: Run tests
        run: |
          cd code/frontend
          npm test || echo "No tests found or tests failed"

  docker-build:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./infrastructure/Dockerfile
          push: false
          tags: optionix/backend:${{ github.sha }}

  build-and-deploy:
    name: Build and Deploy
    needs:
      [
        terraform-validate,
        kubernetes-validate,
        ansible-validate,
        backend-test,
        frontend-test,
        docker-build,
      ]
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Build frontend
        run: |
          cd code/frontend
          npm ci
          npm run build

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f code/backend/requirements.txt ]; then pip install -r code/backend/requirements.txt; fi

      # Deployment steps would go here
      # Example: Deploy to AWS, Kubernetes, etc.
      # These steps should use secrets stored in GitHub Secrets
      # - name: Deploy to production
      #   env:
      #       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #   run: |
      #       echo "Deploy steps here"
