apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-storage
  namespace: monitoring
  labels:
    app: prometheus
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "{{ .Values.monitoring.prometheus.storageClass }}"
  resources:
    requests:
      storage: "{{ .Values.monitoring.prometheus.storage }}"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-storage
  namespace: monitoring
  labels:
    app: grafana
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "{{ .Values.monitoring.grafana.storageClass }}"
  resources:
    requests:
      storage: "{{ .Values.monitoring.grafana.storage }}"
