apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.appName }}-redis"
  namespace: "{{ .Values.namespace }}"
  labels:
    app: "{{ .Values.appName }}-redis"
spec:
  type: ClusterIP
  ports:
    - port: { { .Values.redis.servicePort } }
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    app: "{{ .Values.appName }}-redis"
