---
- name: restart ssh
  systemd:
    name: sshd
    state: restarted
  become: yes

- name: restart fail2ban
  systemd:
    name: fail2ban
    state: restarted
  become: yes

- name: restart auditd
  systemd:
    name: auditd
    state: restarted
  become: yes

- name: restart rsyslog
  systemd:
    name: rsyslog
    state: restarted
  become: yes

- name: restart chrony
  systemd:
    name: chrony
    state: restarted
  become: yes

- name: restart unattended-upgrades
  systemd:
    name: unattended-upgrades
    state: restarted
  become: yes
